file_format: "1"
id: Otter
name: Otter
siblings:
  - Otter_left
  - Otter_right
  - Otter_dongle
type: shield
url: https://github.com/Zettv4/zmk-config-Otter
requires:
  - pro_micro
features:
  - keys
  - studio